name: flutter_carros
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+2
  shared_preferences: ^0.5.6
  sqflite: ^1.3.0+1
  cached_network_image: ^2.2.0+1
  connectivity: ^0.4.8+6
  image_picker: ^0.6.7+1
  provider: ^4.1.3
  share: ^0.6.4+3
  url_launcher: ^5.4.11
  video_player: ^0.10.11+1
  google_maps_flutter: ^0.5.28+1
  flutter_auth_buttons: ^0.8.0

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sql/